/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad
 */
public class MuhammadAnanda extends javax.swing.JFrame {
String angka;
double jumlah,button1,button2;
int pilih;

    /**
     * Creates new form TampilanKalkulator
     */
    public MuhammadAnanda() {
        initComponents();
        angka = "" ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        tampilteks = new javax.swing.JTextField();
        angka9 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        angka7 = new javax.swing.JButton();
        angka4 = new javax.swing.JButton();
        angka1 = new javax.swing.JButton();
        angka0 = new javax.swing.JButton();
        angka2 = new javax.swing.JButton();
        angka5 = new javax.swing.JButton();
        angka8 = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        angka6 = new javax.swing.JButton();
        angka3 = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        btnHasil = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();

        jButton8.setText("jButton1");
        jButton8.setAutoscrolls(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR SEDERHANA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampilteks.setEditable(false);
        tampilteks.setBackground(new java.awt.Color(255, 255, 255));
        tampilteks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tampilteks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tampilteks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilteksActionPerformed(evt);
            }
        });
        getContentPane().add(tampilteks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 90));

        angka9.setBackground(new java.awt.Color(153, 153, 153));
        angka9.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka9.setText("9");
        angka9.setAutoscrolls(true);
        angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ActionPerformed(evt);
            }
        });
        getContentPane().add(angka9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 70));

        hapus.setBackground(new java.awt.Color(153, 153, 153));
        hapus.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        hapus.setText("C");
        hapus.setAutoscrolls(true);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 70));

        angka7.setBackground(new java.awt.Color(153, 153, 153));
        angka7.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka7.setText("7");
        angka7.setAutoscrolls(true);
        angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ActionPerformed(evt);
            }
        });
        getContentPane().add(angka7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 70));

        angka4.setBackground(new java.awt.Color(153, 153, 153));
        angka4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka4.setText("4");
        angka4.setAutoscrolls(true);
        angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ActionPerformed(evt);
            }
        });
        getContentPane().add(angka4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 70));

        angka1.setBackground(new java.awt.Color(153, 153, 153));
        angka1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka1.setText("1");
        angka1.setAutoscrolls(true);
        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });
        getContentPane().add(angka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 70));

        angka0.setBackground(new java.awt.Color(153, 153, 153));
        angka0.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka0.setText("0");
        angka0.setAutoscrolls(true);
        angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ActionPerformed(evt);
            }
        });
        getContentPane().add(angka0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 70));

        angka2.setBackground(new java.awt.Color(153, 153, 153));
        angka2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka2.setText("2");
        angka2.setAutoscrolls(true);
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });
        getContentPane().add(angka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 90, 70));

        angka5.setBackground(new java.awt.Color(153, 153, 153));
        angka5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka5.setText("5");
        angka5.setAutoscrolls(true);
        angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ActionPerformed(evt);
            }
        });
        getContentPane().add(angka5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 70));

        angka8.setBackground(new java.awt.Color(153, 153, 153));
        angka8.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka8.setText("8");
        angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ActionPerformed(evt);
            }
        });
        getContentPane().add(angka8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 70));

        btnKali.setBackground(new java.awt.Color(153, 153, 153));
        btnKali.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnKali.setText("*");
        btnKali.setAutoscrolls(true);
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, 70));

        btnBagi.setBackground(new java.awt.Color(153, 153, 153));
        btnBagi.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnBagi.setText("/");
        btnBagi.setAutoscrolls(true);
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, 70));

        angka6.setBackground(new java.awt.Color(153, 153, 153));
        angka6.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka6.setText("6");
        angka6.setAutoscrolls(true);
        angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ActionPerformed(evt);
            }
        });
        getContentPane().add(angka6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 70));

        angka3.setBackground(new java.awt.Color(153, 153, 153));
        angka3.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        angka3.setText("3");
        angka3.setAutoscrolls(true);
        angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ActionPerformed(evt);
            }
        });
        getContentPane().add(angka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, 70));

        btnKoma.setBackground(new java.awt.Color(153, 153, 153));
        btnKoma.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnKoma.setText(",");
        btnKoma.setAutoscrolls(true);
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, 70));

        btnHasil.setBackground(new java.awt.Color(153, 153, 153));
        btnHasil.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnHasil.setText("=");
        btnHasil.setAutoscrolls(true);
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });
        getContentPane().add(btnHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 90, 70));

        btnTambah.setBackground(new java.awt.Color(153, 153, 153));
        btnTambah.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnTambah.setText("+");
        btnTambah.setAutoscrolls(true);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 90, 70));

        btnkurang.setBackground(new java.awt.Color(153, 153, 153));
        btnkurang.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 13)); // NOI18N
        btnkurang.setText("-");
        btnkurang.setAutoscrolls(true);
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(btnkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        button1=Double.parseDouble(angka);
tampilteks.setText("/");
angka="";
pilih=4;

    }//GEN-LAST:event_btnBagiActionPerformed

    private void angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ActionPerformed
        angka += "8";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka8ActionPerformed

    private void angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ActionPerformed
        angka += "9";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka9ActionPerformed

    private void angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ActionPerformed
        angka += "5";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka5ActionPerformed

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ActionPerformed
        angka += "2";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ActionPerformed
        angka += "6";
        tampilteks.setText(angka) ;
        
    }//GEN-LAST:event_angka6ActionPerformed

    private void tampilteksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilteksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilteksActionPerformed

    private void angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ActionPerformed
        angka += "0";
        tampilteks.setText(angka) ;
        
    }//GEN-LAST:event_angka0ActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        angka += "1";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka1ActionPerformed

    private void angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ActionPerformed
        angka += "3";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka3ActionPerformed

    private void angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ActionPerformed
        angka += "4";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka4ActionPerformed

    private void angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ActionPerformed
        angka += "7";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_angka7ActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
        angka += ".";
        tampilteks.setText(angka) ;
    }//GEN-LAST:event_btnKomaActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        tampilteks.setText ("");
       
        jumlah=0;
        angka= "";
        
        
    }//GEN-LAST:event_hapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       button1=Double.parseDouble(angka);
        tampilteks.setText("+");
        angka="";
        pilih=1;
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        switch(pilih){
        case 1:
            button2 = Double.parseDouble(angka);
            jumlah = button1 + button2;
            angka = Double.toString(jumlah);
            tampilteks.setText(angka);
            break;
        case 2:
            button2 = Double.parseDouble(angka);
            jumlah = button1 - button2;
            angka = Double.toString(jumlah);
            tampilteks.setText(angka);
            break;
        case 3:
            button2 = Double.parseDouble(angka);
            jumlah = button1 * button2;
            angka = Double.toString(jumlah);
            tampilteks.setText(angka);
            break;
        case 4:
            button2 = Double.parseDouble(angka);
            jumlah = button1 / button2;
            angka = Double.toString(jumlah);
            tampilteks.setText(angka);
            break;
            default:
            break;
} 

    }//GEN-LAST:event_btnHasilActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        button1=Double.parseDouble(angka);
tampilteks.setText("-");
angka="";
pilih=2;

    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        button1=Double.parseDouble(angka);
tampilteks.setText("*");
angka="";
pilih=3;

    }//GEN-LAST:event_btnKaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MuhammadAnanda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angka0;
    private javax.swing.JButton angka1;
    private javax.swing.JButton angka2;
    private javax.swing.JButton angka3;
    private javax.swing.JButton angka4;
    private javax.swing.JButton angka5;
    private javax.swing.JButton angka6;
    private javax.swing.JButton angka7;
    private javax.swing.JButton angka8;
    private javax.swing.JButton angka9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnHasil;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton8;
    private javax.swing.JTextField tampilteks;
    // End of variables declaration//GEN-END:variables
}
